Feature/copy no lock files
Tea-n-Tech/chia-tea pull request #58
Opened 2021-11-08 21:15 UTC by tnt-manu

Initial version, lacks proper tests. Worked on local machine with multiple sample files and multiple source directories on two times "task copy".

2021-11-13 14:05 UTC, tnt-codie commented on chia_tea/copy_plots/Disk.py
> +def is_accessible(fpath):
```suggestion
def is_accessible(fpath: str):
```

2021-11-13 14:07 UTC, tnt-codie commented on chia_tea/copy_plots/Disk.py
> +    except Exception:
Would be nice to limit the exception type. Generally we should note what exceptions can occur (including NAS connection issues)

2021-11-13 14:07 UTC, tnt-codie commented on chia_tea/copy_plots/Disk.py
> +def get_files_beingCopied(target_dirs: List[str], files_copied_completely: List[str]) -> List[str]:
```suggestion
def get_files_being_copied(target_dirs: List[str], files_copied_completely: List[str]) -> List[str]:
```

2021-11-13 14:08 UTC, tnt-codie commented on chia_tea/copy_plots/Disk.py
> +    Later
someone was tired I guess

2021-11-13 14:08 UTC, tnt-codie commented on chia_tea/copy_plots/Disk.py
> +        all_files_to_check = [f for f in os.listdir(folder_path) if isfile(join(folder_path, f))]
```suggestion
        all_files_to_check = [f for f in os.listdir(folder_path) if isfile(join(folder_path, f))]
```

2021-11-13 14:12 UTC, tnt-codie commented on chia_tea/copy_plots/Disk.py
> +                all_files_to_check.remove(f)
You are working with Lists here, try using sets. They are made exactly for all that stuff. And use `os.path.samefile` to make sure that relative and absolute filepaths are handled correctly or simply expand all filepaths.

2021-11-13 14:12 UTC, tnt-codie commented on chia_tea/copy_plots/Disk.py
> +    all_filepaths = []
How about renaming this to `filepaths_copied_files`?

2021-11-13 14:14 UTC, tnt-codie commented on chia_tea/copy_plots/__main__.py
>              if successful_copy:
```suggestion
            if not successful_copy:
```

2021-11-13 14:16 UTC, tnt-codie requested changes
Generally I like the solution a lot. Think this is a decent step forward. My only thought is, the feature is so critical, we should write a few unittests for it first. Since there are a lot of side-effects, we definitely need to patch the os functions writing and reading but that is no problem with `unittest.mock`.

2021-11-14 02:01 UTC, tnt-manu commented on chia_tea/copy_plots/Disk.py
> +    Later
that was indeed correct

2021-11-14 02:06 UTC, tnt-manu commented on chia_tea/copy_plots/Disk.py
> +    all_filepaths = []
yes!

2021-11-14 02:10 UTC, tnt-manu commented on chia_tea/copy_plots/Disk.py
> +    except Exception:
not completely sure about the nas connection error ... implemented OSError and FileNotFoundError :)

2021-11-14 02:19 UTC, tnt-manu commented on chia_tea/copy_plots/__main__.py
>              if successful_copy:
? sure ?

2021-11-14 02:20 UTC, tnt-manu commented on chia_tea/copy_plots/Disk.py
> +                all_files_to_check.remove(f)
oh thats a bigger one .. I think I will do that tomorrow with a fresh head ... so its sets for all file lists ?

2021-11-14 20:46 UTC, tnt-codie commented on chia_tea/copy_plots/__main__.py
>              if successful_copy:
You log failed in case of success?

2021-11-14 20:52 UTC, tnt-codie commented on chia_tea/copy_plots/Disk.py
> +        logger.warning(warn_msg, os.path.abspath(fpath))
No `False` on `OSError`?

2021-11-14 20:54 UTC, tnt-codie commented on chia_tea/copy_plots/Disk.py
> +        print("Target:" + folder_path)
Use the logger we have.

2021-12-08 17:35 UTC, codie3611 commented
@tnt-manu I'm still overhauling this PR. Wanna use it in the next release. The testing helped with clearing the code but the os side side effects made testing no fun.

2021-12-14 22:49 UTC, codie3611 approved these changes

2021-12-14 22:49 UTC, merged